
import React, { useState, useEffect, useMemo } from 'react';
import { SetupStep, Config, AppView, DeploymentRecord, ChatMessage, PrivacyThreat, UserRole, ECPAShieldStatus, MockEmail } from './types';
import { DEFAULT_CONFIG, SCRIPTS } from './constants';
import { CodeBlock } from './components/CodeBlock';
import { getExpertAdvice } from './services/geminiService';

const EMAIL_PROVIDERS = [
  { id: 'gmail', name: 'Gmail', icon: 'fab fa-google', color: 'text-red-500' },
  { id: 'outlook', name: 'Outlook', icon: 'fab fa-microsoft', color: 'text-blue-500' },
  { id: 'proton', name: 'Proton', icon: 'fas fa-user-shield', color: 'text-purple-500' },
  { id: 'icloud', name: 'iCloud', icon: 'fas fa-cloud', color: 'text-sky-400' },
  { id: 'yahoo', name: 'Yahoo', icon: 'fab fa-y-combinator', color: 'text-indigo-600' },
  { id: 'custom', name: 'Custom IMAP', icon: 'fas fa-server', color: 'text-slate-400' }
];

const LEGAL_PROTECTIONS = [
  {
    statute: '18 U.S.C. § 2511',
    title: 'Wiretap Act Protection',
    description: 'Prohibits the intentional interception of any wire, oral, or electronic communication.',
    hardening: 'End-to-end ZTNA Encryption'
  },
  {
    statute: '18 U.S.C. § 2701',
    title: 'Stored Communications',
    description: 'Governs voluntary and compelled disclosure of stored wire and electronic communications.',
    hardening: 'Immutable Sovereignty Logs'
  },
  {
    statute: '18 U.S.C. § 3121',
    title: 'Trap and Trace Guard',
    description: 'Restricts the use of pen registers and trap and trace devices on sovereign nodes.',
    hardening: 'Metadata Obfuscation'
  },
  {
    statute: 'Directive 2026-A',
    title: 'Real-time Transparency',
    description: 'Mandates instant user notification for any third-party legal request for communication access.',
    hardening: 'Automated Legal Alerting'
  },
  {
    statute: 'Directive 2026-B',
    title: 'Data Ownership',
    description: 'Legal recognition that data generated by the identity remains the exclusive property of the identity.',
    hardening: 'Self-Sovereign Identity'
  },
  {
    statute: 'Directive 2026-C',
    title: 'Hardened Expiration',
    description: 'Mandatory cryptographic destruction of communication metadata upon session termination.',
    hardening: 'Volatile Storage Policy'
  }
];

const App: React.FC = () => {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [role, setRole] = useState<UserRole>(UserRole.USER);
  const [view, setView] = useState<AppView>(AppView.EMAIL_SCANNER);
  const [activeStep, setActiveStep] = useState<SetupStep>(SetupStep.PREREQUISITES);
  const [config, setConfig] = useState<Config>(DEFAULT_CONFIG);
  const [loadingAdvice, setLoadingAdvice] = useState(false);
  const [query, setQuery] = useState('');
  
  // Login State
  const [emailInput, setEmailInput] = useState('');
  const [isAuthenticating, setIsAuthenticating] = useState(false);

  // Connection Persistence Monitor
  const [connectionStatus, setConnectionStatus] = useState<'stable' | 'optimizing'>('stable');

  // Email Scanner State
  const [isScanning, setIsScanning] = useState(false);
  const [scanProgress, setScanProgress] = useState(0);
  const [emailsToReview, setEmailsToReview] = useState<MockEmail[]>([]);
  const [currentEmailIndex, setCurrentEmailIndex] = useState(0);
  const [nukedCount, setNukedCount] = useState(0);
  const [fortKnoxCount, setFortKnoxCount] = useState(0);
  const [selectedProviders, setSelectedProviders] = useState<string[]>([]);

  // ECPA Shield State
  const [ecpaStatus] = useState<ECPAShieldStatus>({
    protectionActive: true,
    legalRequestsSent: 142,
    lastAudit: new Date().toLocaleDateString(),
    encryptionStandard: 'Post-Quantum Vault 1.0',
    jurisdiction: 'Agape Sovereign Space'
  });

  const [swipeDirection, setSwipeDirection] = useState<'left' | 'right' | null>(null);

  // Undo State
  const [lastAction, setLastAction] = useState<{ index: number, direction: 'left' | 'right', type: 'threat' | 'email' } | null>(null);
  const [showUndo, setShowUndo] = useState(false);

  // Admin States
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [typeFilter, setTypeFilter] = useState<string>('all');
  const [isHealing, setIsHealing] = useState(false);

  const [chatHistory, setChatHistory] = useState<ChatMessage[]>([]);

  const deploySteps = [
    { id: SetupStep.PREREQUISITES, label: 'Cloud Link' },
    { id: SetupStep.TERRAFORM, label: 'Manifest' },
    { id: SetupStep.MCP_SERVER, label: 'Sovereign Node' },
    { id: SetupStep.CLOUDFLARE, label: 'Zero Trust' },
    { id: SetupStep.TROUBLESHOOTING, label: 'Architect AI' }
  ];

  const [myDeployments, setMyDeployments] = useState<DeploymentRecord[]>([
    { id: '1', name: 'Agape Sovereign Hub', type: 'FastMCP', url: 'https://mcp-hello-world-run.a.run.app', status: 'online', timestamp: '2024-05-24', isPinned: true },
    { id: '2', name: 'Identity Oracle', type: 'FastMCP', url: 'https://oracle.run.app', status: 'online', timestamp: '2024-05-25', isPinned: false }
  ]);

  const filteredDeployments = useMemo(() => {
    return myDeployments.filter(d => {
      const statusMatch = statusFilter === 'all' || d.status === statusFilter;
      const typeMatch = typeFilter === 'all' || d.type === typeFilter;
      return statusMatch && typeMatch;
    });
  }, [myDeployments, statusFilter, typeFilter]);

  // Automated AI Greeting on Auth via Zero Trust
  useEffect(() => {
    if (isAuthenticated) {
      const triggerGreeting = async () => {
        setLoadingAdvice(true);
        const greeting = await getExpertAdvice("Generate a powerful, welcoming greeting for a user who has just passed Zero Trust authentication at aitnyc.cloudflareaccess.com. Inform them that their Sovereign node is online and their data is now shielded by the ECPA 2026 framework. Ask them if they are ready to initiate an Inbox Scan.", "Zero Trust Authentication Successful");
        setChatHistory([{
          id: 'greeting',
          role: 'assistant',
          content: greeting || "Zero Trust Verified. Sovereign Node Online. ECPA 2026 Protections Active.",
          timestamp: new Date().toLocaleTimeString()
        }]);
        setLoadingAdvice(false);
      };
      triggerGreeting();

      // Persistence Monitor interval
      const monitor = setInterval(() => {
        setConnectionStatus(prev => prev === 'stable' ? 'optimizing' : 'stable');
      }, 5000);
      return () => clearInterval(monitor);
    }
  }, [isAuthenticated]);

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    if (!emailInput) return;
    setIsAuthenticating(true);
    // Mimic Zero Trust verification
    const isAdmin = emailInput.toLowerCase() === 'idin@agape.nyc';
    setTimeout(() => {
      setIsAuthenticated(true);
      setRole(isAdmin ? UserRole.ADMIN : UserRole.USER);
      setView(isAdmin ? AppView.DASHBOARD : AppView.EMAIL_SCANNER);
      setIsAuthenticating(false);
    }, 1800);
  };

  const handleStartEmailScan = (isGlobal: boolean) => {
    if (!isGlobal && selectedProviders.length === 0) {
      alert("Please select at least one provider for a selective scan.");
      return;
    }
    setIsScanning(true);
    setScanProgress(0);
    const interval = setInterval(() => {
      setScanProgress(prev => {
        if (prev >= 100) {
          clearInterval(interval);
          finishScan();
          return 100;
        }
        return prev + 1;
      });
    }, 50);
  };

  const finishScan = () => {
    setTimeout(() => {
      setEmailsToReview([
        { id: 'e1', sender: 'Ad-Network Delta', subject: 'Your preferences updated', preview: 'We noticed your recent activity on Sovereign sites...', riskReason: 'Unauthorized cross-site tracking fragment detected.', category: 'Tracker' },
        { id: 'e2', sender: 'DataHarvester Corp', subject: 'Inquiry regarding identity', preview: 'Verify your associated shadow profiles for optimization...', riskReason: 'ECPA 2026 Violation: Non-consensual shadow profiling.', category: 'ECPA Violation' },
        { id: 'e3', sender: 'PromoBlast VIP', subject: 'YOU WON A NEW PHONE!', preview: 'Click to claim your prize from our partners...', riskReason: 'Dark pattern engagement trap with hidden metadata logging.', category: 'Dark Pattern' },
        { id: 'e4', sender: 'Unknown Entity', subject: 'Archive request', preview: 'Accessing your historical communications for indexing...', riskReason: 'Aggressive data broker scraping attempt.', category: 'Data Harvest' },
      ]);
      setIsScanning(false);
    }, 1000);
  };

  const handleSwipe = (direction: 'left' | 'right', type: 'threat' | 'email') => {
    const isEmail = type === 'email';
    setLastAction({ index: isEmail ? currentEmailIndex : 0, direction, type });
    setShowUndo(true);
    setSwipeDirection(direction);
    
    // Increased duration for a smoother visual exit
    setTimeout(() => {
      if (isEmail) {
        if (direction === 'left') setNukedCount(prev => prev + 1);
        else setFortKnoxCount(prev => prev + 1);
        setCurrentEmailIndex(prev => prev + 1);
      }
      setSwipeDirection(null);
    }, 500); // Wait for the transition to finish

    setTimeout(() => setShowUndo(false), 5000);
  };

  const handleUndo = () => {
    if (!lastAction) return;
    if (lastAction.type === 'email') {
      setCurrentEmailIndex(lastAction.index);
      if (lastAction.direction === 'left') setNukedCount(prev => Math.max(0, prev - 1));
      else setFortKnoxCount(prev => Math.max(0, prev - 1));
    }
    setLastAction(null);
    setShowUndo(false);
  };

  const handleHealNode = (id: string) => {
    setIsHealing(true);
    setTimeout(() => {
      setMyDeployments(prev => prev.map(d => d.id === id ? { ...d, status: 'online' as const } : d));
      setIsHealing(false);
    }, 2500);
  };

  const toggleProvider = (id: string) => {
    setSelectedProviders(prev => 
      prev.includes(id) ? prev.filter(p => p !== id) : [...prev, id]
    );
  };

  const handleAdvice = async () => {
    if (!query.trim()) return;
    const currentQuery = query;
    setQuery('');
    setLoadingAdvice(true);

    const userMsg: ChatMessage = {
      id: Date.now().toString(),
      role: 'user',
      content: currentQuery,
      timestamp: new Date().toLocaleTimeString()
    };
    
    setChatHistory(prev => [...prev, userMsg]);

    try {
      const context = `Context: User is on ${view} view with role ${role}. Security Tunnel: aitnyc.cloudflareaccess.com. Governance: ECPA 2026.`;
      const response = await getExpertAdvice(currentQuery, context);

      const assistantMsg: ChatMessage = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: response || "Secure link established, but the sovereign response was empty. Please check your cluster health.",
        timestamp: new Date().toLocaleTimeString()
      };

      setChatHistory(prev => [...prev, assistantMsg]);
    } catch (err) {
      console.error("Architect AI Advice Error:", err);
    } finally {
      setLoadingAdvice(false);
    }
  };

  if (!isAuthenticated) {
    return (
      <div className="min-h-screen bg-[#020617] text-slate-100 flex items-center justify-center p-8 font-inter overflow-hidden relative">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,_var(--tw-gradient-stops))] from-blue-900/40 via-transparent to-transparent opacity-40"></div>
        <div className="max-w-xl w-full animate-in fade-in zoom-in duration-1000">
          <div className="glass-card rounded-[4rem] p-16 border border-white/5 shadow-2xl relative overflow-hidden text-center">
            <div className="w-32 h-32 bg-gradient-to-br from-blue-600 to-indigo-700 rounded-[2.5rem] flex items-center justify-center mx-auto mb-12 shadow-3xl border border-white/10 relative z-10 group hover:rotate-6 transition-transform">
              <i className="fas fa-shield-cat text-white text-6xl"></i>
            </div>
            <h1 className="text-6xl font-black text-white mb-4 tracking-tighter uppercase leading-none">Sovereign</h1>
            <p className="text-slate-500 font-medium mb-12 text-xl tracking-tight">aitnyc.cloudflareaccess.com</p>
            <form onSubmit={handleLogin} className="space-y-6">
              <input 
                type="email"
                required
                value={emailInput}
                onChange={e => setEmailInput(e.target.value)}
                placeholder="identity@agape.nyc"
                className="w-full bg-slate-900/80 border border-white/10 rounded-[2rem] px-10 py-7 text-white focus:outline-none focus:ring-4 focus:ring-blue-600/20 transition-all font-medium placeholder:text-slate-700 text-xl shadow-inner"
              />
              <button 
                type="submit"
                disabled={isAuthenticating}
                className="w-full py-7 bg-blue-600 hover:bg-blue-500 text-white rounded-[2rem] font-black uppercase tracking-widest text-sm shadow-3xl transition-all hover:-translate-y-1 active:scale-95 flex items-center justify-center gap-3"
              >
                {isAuthenticating && <i className="fas fa-spinner fa-spin"></i>}
                {isAuthenticating ? "Verifying Zero Trust..." : "Unlock Portal"}
              </button>
            </form>
            <p className="mt-12 text-[10px] font-black text-slate-700 uppercase tracking-[0.5em]">Protected by ECPA 2026 Framework</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#020617] text-slate-100 flex overflow-hidden font-inter">
      {/* Sidebar - Sovereign Identity Style */}
      <aside className="w-80 border-r border-white/5 bg-[#0a1024]/95 backdrop-blur-3xl flex flex-col h-screen sticky top-0 shadow-2xl z-[100]">
        <div className="p-10 flex flex-col h-full">
          <div className="flex items-center gap-4 mb-16 group cursor-pointer" onClick={() => setView(role === UserRole.ADMIN ? AppView.DASHBOARD : AppView.EMAIL_SCANNER)}>
            <div className="w-14 h-14 bg-gradient-to-br from-blue-600 to-indigo-700 rounded-2xl flex items-center justify-center shadow-2xl group-hover:scale-105 transition-transform border border-white/10">
              <i className="fas fa-shield-cat text-white text-3xl"></i>
            </div>
            <div>
              <h1 className="text-[10px] font-black tracking-[0.5em] text-white uppercase opacity-30 mb-1">Agape</h1>
              <h2 className="text-xl font-bold text-blue-400 tracking-tighter leading-none">Sovereign</h2>
            </div>
          </div>

          <nav className="space-y-4 mb-10">
            <button onClick={() => setView(AppView.EMAIL_SCANNER)} className={`w-full flex items-center gap-6 px-7 py-6 rounded-3xl text-[12px] font-black uppercase tracking-[0.2em] transition-all ${view === AppView.EMAIL_SCANNER ? 'bg-blue-600 text-white shadow-3xl' : 'text-slate-500 hover:text-white hover:bg-white/5'}`}>
              <i className="fas fa-mailbox text-xl"></i> Inbox Scan
            </button>
            <button onClick={() => setView(AppView.ECPA_SHIELD)} className={`w-full flex items-center gap-6 px-7 py-6 rounded-3xl text-[12px] font-black uppercase tracking-[0.2em] transition-all ${view === AppView.ECPA_SHIELD ? 'bg-indigo-600 text-white shadow-3xl' : 'text-slate-500 hover:text-white hover:bg-white/5'}`}>
              <i className="fas fa-landmark text-xl"></i> ECPA Status
            </button>
            <button onClick={() => setView(AppView.CHAT)} className={`w-full flex items-center gap-6 px-7 py-6 rounded-3xl text-[12px] font-black uppercase tracking-[0.2em] transition-all ${view === AppView.CHAT ? 'bg-slate-100 text-black shadow-3xl' : 'text-slate-500 hover:text-white hover:bg-white/5'}`}>
              <i className="fas fa-brain text-xl"></i> Architect AI
            </button>

            {role === UserRole.ADMIN && (
              <div className="pt-8 mt-8 border-t border-white/5 space-y-3">
                <p className="px-7 mb-4 text-[10px] font-black uppercase tracking-[0.5em] text-slate-700">Cluster Admin</p>
                <button onClick={() => setView(AppView.DASHBOARD)} className={`w-full flex items-center gap-6 px-7 py-5 rounded-2xl text-[11px] font-black uppercase tracking-[0.2em] transition-all ${view === AppView.DASHBOARD ? 'bg-slate-800 text-blue-400 border border-blue-500/30' : 'text-slate-500 hover:text-white hover:bg-white/5'}`}>
                  <i className="fas fa-grid-2 text-lg"></i> Nodes
                </button>
                <button onClick={() => setView(AppView.DEPLOY)} className={`w-full flex items-center gap-6 px-7 py-5 rounded-2xl text-[11px] font-black uppercase tracking-[0.2em] transition-all ${view === AppView.DEPLOY ? 'bg-slate-800 text-blue-400 border border-blue-500/30' : 'text-slate-500 hover:text-white hover:bg-white/5'}`}>
                  <i className="fas fa-terminal text-lg"></i> Provision
                </button>
              </div>
            )}
          </nav>

          <div className="mt-auto">
            <div className="bg-slate-900/60 rounded-[2.5rem] p-8 border border-white/5 mb-8 relative overflow-hidden group">
              <div className="absolute inset-0 bg-blue-500/5 opacity-0 group-hover:opacity-100 transition-opacity"></div>
              <p className="text-[10px] text-slate-600 font-black uppercase tracking-[0.4em] mb-4">Sovereign Tunnel</p>
              <p className="text-sm text-blue-200 font-mono font-bold truncate mb-4">aitnyc.cloudflareaccess.com</p>
              <div className="flex items-center justify-between">
                 <span className={`text-[10px] font-black uppercase tracking-[0.2em] ${connectionStatus === 'stable' ? 'text-green-500' : 'text-blue-400'}`}>
                    {connectionStatus === 'stable' ? 'Persistence Stable' : 'Tunnel Optimizing'}
                 </span>
                 <div className={`w-3 h-3 rounded-full animate-pulse ${connectionStatus === 'stable' ? 'bg-green-500 shadow-[0_0_15px_rgba(34,197,94,1)]' : 'bg-blue-500 shadow-[0_0_15px_rgba(59,130,246,1)]'}`}></div>
              </div>
            </div>
            <button onClick={() => setIsAuthenticated(false)} className="w-full py-4 bg-red-600/10 hover:bg-red-600 hover:text-white text-red-500 rounded-2xl text-[10px] font-black uppercase tracking-[0.5em] transition-all">
              <i className="fas fa-power-off mr-3"></i> Terminate Link
            </button>
          </div>
        </div>
      </aside>

      <main className="flex-1 flex flex-col h-screen overflow-hidden relative bg-[#020617]">
        <header className="h-28 border-b border-white/5 flex items-center px-16 justify-between bg-[#020617]/90 backdrop-blur-3xl z-[90]">
          <div className="flex items-center gap-8">
            <div className="text-[12px] font-black text-slate-600 uppercase tracking-[0.6em]">Agape Sovereign</div>
            <i className="fas fa-angle-right text-slate-800 text-sm"></i>
            <div className="text-[12px] font-black text-blue-500 uppercase tracking-[0.6em]">{view.replace('_', ' ')}</div>
          </div>
          <div className="flex items-center gap-6">
            <div className="px-6 py-2.5 bg-green-500/5 border border-green-500/20 rounded-full flex items-center gap-3">
               <span className="text-[11px] font-black uppercase text-green-500 tracking-[0.2em]">ZTNA SECURE</span>
            </div>
          </div>
        </header>

        <div className="flex-1 overflow-y-auto p-16 custom-scrollbar relative z-10">
          <div className="max-w-6xl mx-auto w-full">
            
            {/* EMAIL SCANNER: Revolving Animated UI */}
            {view === AppView.EMAIL_SCANNER && (
              <div className="max-w-4xl mx-auto space-y-12 animate-in fade-in duration-1000">
                {!isScanning && emailsToReview.length === 0 && (
                   <div className="text-center space-y-12 py-10">
                      <div className="w-56 h-56 bg-blue-600/5 rounded-full mx-auto flex items-center justify-center relative">
                        <div className="absolute inset-0 rounded-full border-2 border-blue-500/10 animate-[ping_3s_infinite]"></div>
                        <div className="absolute inset-4 border-b-4 border-blue-500/40 rounded-full animate-spin-slow"></div>
                        <i className="fas fa-mailbox text-8xl text-blue-500"></i>
                      </div>
                      <div className="space-y-4">
                        <h2 className="text-7xl font-black text-white uppercase tracking-tighter leading-none">Privacy Audit</h2>
                        <p className="text-slate-400 text-xl font-medium max-w-2xl mx-auto tracking-tight leading-relaxed">
                          Sovereign AI intelligence is ready to scan your communications for ECPA 2026 non-compliance.
                        </p>
                      </div>

                      {/* Provider Selection Section */}
                      <div className="max-w-3xl mx-auto space-y-10 py-12 px-10 glass-card rounded-[4rem] border-white/5 shadow-inner">
                        <div className="space-y-2">
                          <p className="text-[12px] font-black text-blue-500 uppercase tracking-[0.6em]">Target Platforms</p>
                          <p className="text-slate-500 text-sm font-medium">Select specific providers for a localized sovereign scan</p>
                        </div>
                        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                          {EMAIL_PROVIDERS.map(provider => (
                            <button
                              key={provider.id}
                              onClick={() => toggleProvider(provider.id)}
                              className={`group flex items-center gap-6 px-8 py-6 rounded-[2rem] border transition-all duration-300 relative overflow-hidden ${
                                selectedProviders.includes(provider.id) 
                                  ? 'bg-blue-600/20 border-blue-500/50 shadow-[0_10px_30px_rgba(59,130,246,0.1)]' 
                                  : 'bg-slate-900/40 border-white/5 hover:border-white/10 hover:bg-slate-800/40'
                              }`}
                            >
                              <div className={`w-12 h-12 rounded-xl bg-slate-800/50 flex items-center justify-center transition-transform group-hover:scale-110 ${selectedProviders.includes(provider.id) ? 'scale-110 bg-blue-500/10' : ''}`}>
                                <i className={`${provider.icon} text-2xl ${provider.color}`}></i>
                              </div>
                              <div className="text-left">
                                <span className={`text-[12px] font-black uppercase tracking-widest block transition-colors ${selectedProviders.includes(provider.id) ? 'text-white' : 'text-slate-500'}`}>{provider.name}</span>
                                {selectedProviders.includes(provider.id) && (
                                  <span className="text-[9px] font-black uppercase tracking-widest text-blue-400 animate-in fade-in slide-in-from-left-2">Targeted</span>
                                )}
                              </div>
                              {selectedProviders.includes(provider.id) && (
                                <div className="ml-auto w-2 h-2 bg-blue-500 rounded-full shadow-[0_0_10px_rgba(59,130,246,1)]"></div>
                              )}
                            </button>
                          ))}
                        </div>
                      </div>

                      <div className="flex flex-col md:flex-row gap-8 justify-center pt-8">
                        <button 
                          onClick={() => handleStartEmailScan(true)}
                          className="group px-24 py-10 bg-blue-600 hover:bg-blue-500 rounded-[3rem] font-black uppercase tracking-[0.5em] text-xs shadow-3xl transition-all hover:-translate-y-2 active:scale-95 flex items-center justify-center gap-4"
                        >
                          <i className="fas fa-globe-americas group-hover:rotate-12 transition-transform"></i> Full Audit
                        </button>
                        <button 
                          onClick={() => handleStartEmailScan(false)}
                          disabled={selectedProviders.length === 0}
                          className="group px-24 py-10 bg-slate-100 hover:bg-white text-black disabled:opacity-20 disabled:cursor-not-allowed rounded-[3rem] font-black uppercase tracking-[0.5em] text-xs shadow-3xl transition-all hover:-translate-y-2 active:scale-95 flex items-center justify-center gap-4 border border-white/10"
                        >
                          <i className="fas fa-crosshairs group-hover:scale-110 transition-transform"></i> Provider Scan
                        </button>
                      </div>
                   </div>
                )}

                {isScanning && (
                   <div className="flex flex-col items-center justify-center py-20 space-y-20">
                      <div className="relative w-96 h-96">
                         <div className="absolute inset-0 border-8 border-t-blue-600 border-r-transparent border-b-indigo-600 border-l-transparent rounded-full animate-spin-fast"></div>
                         <div className="absolute inset-8 border-4 border-t-transparent border-r-cyan-500 border-b-transparent border-l-purple-500 rounded-full animate-spin-slow"></div>
                         <div className="absolute inset-16 border-2 border-slate-700 rounded-full flex items-center justify-center">
                            <div className="text-center">
                               <span className="text-6xl font-black text-white">{scanProgress}%</span>
                               <p className="text-[10px] font-black text-blue-500 uppercase tracking-[0.5em] mt-3">Sovereign Scan</p>
                            </div>
                         </div>
                      </div>
                      <div className="text-center space-y-6">
                        <p className="text-slate-500 font-mono text-lg animate-pulse">Scanning 18 U.S.C. §§ 2510-2523 Violations...</p>
                        <div className="flex gap-4 justify-center">
                           <span className="px-6 py-2 bg-slate-900 border border-white/5 rounded-full text-[10px] font-black uppercase text-blue-400 tracking-widest">Metadata Auditing</span>
                           <span className="px-6 py-2 bg-slate-900 border border-white/5 rounded-full text-[10px] font-black uppercase text-purple-400 tracking-widest">Entity Removal Ready</span>
                        </div>
                      </div>
                   </div>
                )}

                {!isScanning && emailsToReview.length > 0 && currentEmailIndex < emailsToReview.length && (
                  <div className="max-w-2xl mx-auto space-y-12 relative animate-in fade-in duration-500">
                    <div className="text-center space-y-4">
                      <h3 className="text-5xl font-black text-white uppercase tracking-tighter">Decision Engine</h3>
                      <div className="flex items-center justify-center gap-10">
                        <span className="text-red-500 font-black uppercase tracking-widest text-[11px] animate-pulse">← NUKE (DELETE)</span>
                        <div className="w-1 h-1 bg-slate-800 rounded-full"></div>
                        <span className="text-blue-500 font-black uppercase tracking-widest text-[11px] animate-pulse">FORT KNOX (KEEP) →</span>
                      </div>
                    </div>

                    <div className="relative h-[650px] flex items-center justify-center">
                      {showUndo && (
                        <div className="absolute -top-12 z-50 animate-in fade-in slide-in-from-top-4">
                          <button onClick={handleUndo} className="bg-slate-100 text-black px-10 py-4 rounded-2xl font-black uppercase tracking-widest text-[11px] shadow-3xl flex items-center gap-3 transition-transform hover:scale-105 active:scale-95">
                             <i className="fas fa-rotate-left"></i> Undo Decision
                          </button>
                        </div>
                      )}

                      {emailsToReview.slice(currentEmailIndex, currentEmailIndex + 1).map(email => (
                         <div 
                          key={email.id} 
                          className={`absolute inset-0 transition-all duration-700 ease-[cubic-bezier(0.23,1,0.32,1)] transform origin-bottom ${
                            swipeDirection === 'left' ? '-translate-x-[250%] -rotate-[45deg] scale-90 opacity-0 blur-sm' : 
                            swipeDirection === 'right' ? 'translate-x-[250%] rotate-[45deg] scale-90 opacity-0 blur-sm' : 'translate-x-0 rotate-0 opacity-100'
                          }`}
                         >
                            <div className="glass-card rounded-[4rem] p-16 h-full border border-white/10 shadow-3xl flex flex-col justify-between overflow-hidden relative group">
                               {/* Animated Overlay Stickers for Reinforcement */}
                               <div className={`absolute inset-0 z-40 flex items-center justify-center pointer-events-none transition-opacity duration-300 ${swipeDirection === 'left' ? 'opacity-100' : 'opacity-0'}`}>
                                  <div className="px-12 py-6 border-8 border-red-500 rounded-2xl transform -rotate-12 bg-red-950/20 backdrop-blur-sm">
                                     <span className="text-6xl font-black text-red-500 uppercase tracking-tighter">NUKE</span>
                                  </div>
                               </div>
                               <div className={`absolute inset-0 z-40 flex items-center justify-center pointer-events-none transition-opacity duration-300 ${swipeDirection === 'right' ? 'opacity-100' : 'opacity-0'}`}>
                                  <div className="px-12 py-6 border-8 border-blue-500 rounded-2xl transform rotate-12 bg-blue-950/20 backdrop-blur-sm">
                                     <span className="text-6xl font-black text-blue-500 uppercase tracking-tighter">SECURED</span>
                                  </div>
                               </div>

                               <div className="absolute top-0 left-0 w-full h-3 bg-gradient-to-r from-red-600 via-blue-600 to-indigo-600"></div>
                               <div className="space-y-10">
                                  <div className="flex justify-between items-start">
                                     <div className={`px-6 py-2 rounded-full border ${email.category === 'ECPA Violation' ? 'bg-red-500/10 border-red-500/30 text-red-500' : 'bg-blue-500/10 border-blue-500/30 text-blue-500'}`}>
                                        <span className="text-[11px] font-black uppercase tracking-widest">{email.category}</span>
                                     </div>
                                     <i className="fas fa-shield-virus text-slate-800 text-4xl"></i>
                                  </div>
                                  <div>
                                     <p className="text-[11px] font-black text-slate-700 uppercase tracking-[0.5em] mb-4">Origin Entity</p>
                                     <h4 className="text-4xl font-black text-white uppercase tracking-tighter leading-none">{email.sender}</h4>
                                  </div>
                                  <div className="bg-slate-900/80 p-8 rounded-[2.5rem] border border-white/5 relative">
                                     <p className="text-[11px] font-black text-slate-700 uppercase tracking-[0.5em] mb-4">Content Preview</p>
                                     <p className="text-xl text-slate-300 font-medium italic">"{email.preview}..."</p>
                                     <div className="absolute -top-4 -right-4 w-12 h-12 bg-blue-600 rounded-2xl flex items-center justify-center text-white shadow-3xl">
                                        <i className="fas fa-magnifying-glass-chart"></i>
                                     </div>
                                  </div>
                                  <div className="bg-red-600/5 p-8 rounded-[2.5rem] border border-red-500/10">
                                     <p className="text-[11px] font-black text-red-500 uppercase tracking-widest mb-3">Architect AI Analysis</p>
                                     <p className="text-lg text-red-400 font-bold leading-snug">{email.riskReason}</p>
                                  </div>
                               </div>
                               <div className="flex gap-8 mt-12">
                                  <button onClick={() => handleSwipe('left', 'email')} className="flex-1 py-9 bg-red-600 hover:bg-red-500 text-white rounded-[2.5rem] font-black uppercase tracking-[0.5em] text-sm shadow-3xl transition-all hover:-translate-y-2 active:scale-95 flex items-center justify-center gap-4">
                                    <i className="fas fa-biohazard text-xl"></i> NUKE
                                  </button>
                                  <button onClick={() => handleSwipe('right', 'email')} className="flex-1 py-9 bg-blue-600 hover:bg-blue-500 text-white rounded-[2.5rem] font-black uppercase tracking-[0.5em] text-sm shadow-3xl transition-all hover:-translate-y-2 active:scale-95 flex items-center justify-center gap-4">
                                    FORT KNOX <i className="fas fa-vault text-xl"></i>
                                  </button>
                               </div>
                            </div>
                         </div>
                      ))}
                    </div>
                  </div>
                )}

                {emailsToReview.length > 0 && currentEmailIndex >= emailsToReview.length && (
                   <div className="text-center space-y-16 py-20 animate-in zoom-in-95 duration-1000">
                      <div className="w-56 h-56 bg-green-500/10 rounded-[4.5rem] mx-auto flex items-center justify-center border-2 border-green-500/30 shadow-[0_0_80px_rgba(34,197,94,0.1)]">
                         <i className="fas fa-shield-check text-9xl text-green-500"></i>
                      </div>
                      <div className="space-y-6">
                        <h2 className="text-8xl font-black text-white uppercase tracking-tighter leading-none">Audit Finished</h2>
                        <p className="text-slate-400 text-3xl font-medium tracking-tight">Sovereignty Re-established via ECPA Hardening.</p>
                      </div>
                      <div className="grid grid-cols-2 gap-12 max-w-2xl mx-auto">
                         <div className="glass-card p-12 rounded-[4rem] border-red-500/20 shadow-3xl hover:border-red-500/40 transition-all">
                            <p className="text-7xl font-black text-red-500">{nukedCount}</p>
                            <p className="text-[12px] font-black text-slate-600 uppercase tracking-[0.5em] mt-4">Entities Nuked</p>
                         </div>
                         <div className="glass-card p-12 rounded-[4rem] border-blue-500/20 shadow-3xl hover:border-blue-500/40 transition-all">
                            <p className="text-7xl font-black text-blue-500">{fortKnoxCount}</p>
                            <p className="text-[12px] font-black text-slate-600 uppercase tracking-[0.5em] mt-4">Safe in Fort Knox</p>
                         </div>
                      </div>
                      <button onClick={() => { setEmailsToReview([]); setCurrentEmailIndex(0); setNukedCount(0); setFortKnoxCount(0); setSelectedProviders([]); }} className="px-24 py-9 bg-slate-800 hover:bg-slate-700 text-white rounded-[3rem] font-black uppercase tracking-[0.6em] text-xs transition-all shadow-3xl active:scale-95">Return to Portal</button>
                   </div>
                )}
              </div>
            )}

            {/* CHAT / ADVICE VIEW */}
            {view === AppView.CHAT && (
              <div className="max-w-4xl mx-auto space-y-12 animate-in slide-in-from-bottom-12 duration-1000">
                <div className="text-center mb-12">
                   <h2 className="text-7xl font-black text-white uppercase tracking-tighter leading-none">Architect Intelligence</h2>
                   <p className="text-slate-500 text-xl mt-4 font-medium tracking-tight">Active session with Sovereign Node via aitnyc.cloudflareaccess.com</p>
                </div>
                <div className="space-y-12 min-h-[500px]">
                  {chatHistory.map(msg => (
                    <div key={msg.id} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                       <div className={`max-w-[85%] rounded-[3.5rem] p-12 text-2xl leading-relaxed shadow-3xl border transition-all ${
                         msg.role === 'user' ? 'bg-blue-600 text-white border-blue-500' : 'bg-slate-900/90 border-white/5 text-slate-300'
                       }`}>
                          <p className="font-medium">"{msg.content}"</p>
                       </div>
                    </div>
                  ))}
                  {loadingAdvice && (
                    <div className="flex justify-start">
                       <div className="bg-slate-900 rounded-[3rem] px-12 py-8 border border-white/5 flex items-center gap-10 animate-pulse">
                          <i className="fas fa-brain-circuit text-blue-500 text-4xl animate-spin-slow"></i>
                          <span className="text-[14px] font-black uppercase tracking-[0.6em] text-slate-700">Thinking...</span>
                       </div>
                    </div>
                  )}
                </div>
                <div className="relative pt-12 border-t border-white/5">
                   <input 
                    type="text" 
                    value={query}
                    onChange={e => setQuery(e.target.value)}
                    onKeyPress={e => e.key === 'Enter' && handleAdvice()}
                    className="w-full bg-slate-900 border border-white/10 rounded-[3rem] px-16 py-10 text-2xl focus:ring-4 focus:ring-blue-600/20 outline-none shadow-3xl pr-64"
                    placeholder="Consult your Sovereign Node..."
                   />
                   <button 
                    onClick={handleAdvice}
                    className="absolute right-8 top-[calc(3rem+12px)] px-16 py-7 bg-blue-600 text-white rounded-[2rem] font-black uppercase tracking-widest text-xs shadow-3xl active:scale-95"
                   >
                     TRANSMIT
                   </button>
                </div>
              </div>
            )}

            {/* ECPA SHIELD VIEW */}
            {view === AppView.ECPA_SHIELD && (
              <div className="max-w-6xl mx-auto space-y-20 animate-in fade-in duration-1000">
                <div className="text-center">
                  <h2 className="text-8xl font-black text-white mb-8 tracking-tighter uppercase leading-none">ECPA Shield</h2>
                  <p className="text-slate-400 text-3xl font-medium tracking-tight italic">Digital Sovereignty via 18 U.S.C. §§ 2510-2523 Enforcement</p>
                </div>
                
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-16">
                   <div className="glass-card rounded-[5rem] p-16 border-l-[20px] border-l-blue-600 shadow-3xl transition-transform hover:-translate-y-2">
                      <h3 className="text-4xl font-black mb-12 text-white uppercase tracking-tighter">Hardened Path</h3>
                      <div className="space-y-10">
                         <div className="flex justify-between items-center py-6 border-b border-white/5">
                            <span className="text-slate-600 font-black uppercase tracking-[0.4em] text-[12px]">Framework</span>
                            <span className="text-slate-100 font-black uppercase tracking-[0.4em] text-[14px]">ECPA 2026 Ready</span>
                         </div>
                         <div className="flex justify-between items-center py-6 border-b border-white/5">
                            <span className="text-slate-600 font-black uppercase tracking-[0.4em] text-[12px]">Zero Trust</span>
                            <span className="text-green-500 font-black uppercase tracking-[0.4em] text-[14px]">Verified Tunnel</span>
                         </div>
                         <div className="flex justify-between items-center py-6">
                            <span className="text-slate-600 font-black uppercase tracking-[0.4em] text-[12px]">Legal Guard</span>
                            <span className="text-blue-500 font-black uppercase tracking-[0.4em] text-[14px]">18 U.S.C. §§ 2510</span>
                         </div>
                      </div>
                   </div>
                   <div className="glass-card rounded-[5rem] p-16 border border-white/5 flex flex-col justify-center gap-10 shadow-3xl bg-slate-900/40 relative overflow-hidden group">
                      <div className="absolute inset-0 bg-blue-600/5 opacity-0 group-hover:opacity-100 transition-opacity"></div>
                      <p className="text-slate-300 text-2xl font-medium leading-relaxed italic tracking-tight relative z-10">
                        "{SCRIPTS.ECPA_FULL_NOTICE}"
                      </p>
                      <button className="px-16 py-7 bg-white text-black rounded-[2.5rem] font-black uppercase tracking-[0.5em] text-xs shadow-3xl transition-all active:scale-95 relative z-10">Download Compliance Audit</button>
                   </div>
                </div>

                {/* New Legal Protections Section */}
                <div className="space-y-12 py-16">
                  <div className="flex items-center gap-8 mb-4">
                     <h3 className="text-5xl font-black text-white uppercase tracking-tighter">Sovereign Legal Framework</h3>
                     <div className="h-1 flex-1 bg-slate-800 rounded-full"></div>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-8">
                    {LEGAL_PROTECTIONS.map((protection, idx) => (
                      <div key={idx} className="glass-card p-12 rounded-[4rem] border border-white/5 shadow-2xl hover:border-blue-500/20 transition-all flex flex-col justify-between group">
                        <div className="space-y-6">
                          <div className="flex justify-between items-start">
                             <span className="text-[12px] font-black text-blue-500 font-mono tracking-widest">{protection.statute}</span>
                             <div className="w-10 h-10 bg-slate-900 rounded-2xl flex items-center justify-center text-slate-700 group-hover:text-blue-500 transition-colors">
                               <i className="fas fa-gavel text-sm"></i>
                             </div>
                          </div>
                          <h4 className="text-2xl font-black text-white uppercase tracking-tight">{protection.title}</h4>
                          <p className="text-slate-400 text-lg leading-relaxed font-medium">
                            {protection.description}
                          </p>
                        </div>
                        <div className="mt-10 pt-8 border-t border-white/5 flex items-center justify-between">
                           <span className="text-[10px] font-black text-slate-600 uppercase tracking-[0.4em]">2026 Hardening</span>
                           <span className="px-4 py-1.5 bg-green-500/10 text-green-500 border border-green-500/20 rounded-full text-[9px] font-black uppercase tracking-widest">{protection.hardening}</span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {/* ADMIN DASHBOARD */}
            {role === UserRole.ADMIN && view === AppView.DASHBOARD && (
              <div className="space-y-16 animate-in fade-in duration-700">
                <div className="flex flex-col md:flex-row md:items-end justify-between border-b border-white/5 pb-16 gap-10">
                  <div>
                    <h2 className="text-8xl font-black text-white mb-8 tracking-tighter uppercase leading-none">Cluster Status</h2>
                    <p className="text-slate-400 text-3xl font-medium tracking-tight">Architect Level: aitnyc.cloudflareaccess.com</p>
                  </div>
                  <button onClick={() => setView(AppView.DEPLOY)} className="px-16 py-7 bg-blue-600 hover:bg-blue-500 rounded-[2.5rem] font-black uppercase tracking-widest text-sm shadow-3xl transition-all">Provision Sovereign Node</button>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-16">
                   {filteredDeployments.map(item => (
                    <div key={item.id} className="glass-card rounded-[4.5rem] p-16 relative group border border-white/5 shadow-3xl transition-all hover:scale-105">
                      <div className={`w-28 h-28 rounded-[3rem] flex items-center justify-center text-5xl mb-12 border transition-colors ${item.status === 'online' ? 'bg-green-500/10 border-green-500/30 text-green-500' : 'bg-red-500/10 border-red-500/30 text-red-500'}`}>
                        <i className={`fas ${item.status === 'online' ? 'fa-bolt' : 'fa-triangle-exclamation'}`}></i>
                      </div>
                      <h3 className="text-4xl font-black text-white mb-4 tracking-tighter uppercase">{item.name}</h3>
                      <div className="flex items-center gap-4 mb-10">
                        <span className="px-6 py-2 bg-green-500/10 text-green-500 border border-green-500/20 rounded-full text-[11px] font-black uppercase tracking-widest rounded-xl">STABLE</span>
                        <p className="text-[11px] text-slate-700 font-black uppercase tracking-[0.4em]">{item.type}</p>
                      </div>
                      <div className="bg-black/60 p-8 rounded-3xl border border-white/5 text-sm font-mono text-blue-300/60 truncate mb-12">
                        {item.url}
                      </div>
                      <button className="w-full py-6 bg-slate-800 hover:bg-slate-700 rounded-3xl text-[11px] font-black uppercase tracking-[0.5em] transition-all">Audit Node</button>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* DEPLOY VIEW */}
            {role === UserRole.ADMIN && view === AppView.DEPLOY && (
              <div className="max-w-4xl mx-auto space-y-16 animate-in slide-in-from-right-12 duration-1000">
                <div className="text-center">
                   <h2 className="text-8xl font-black text-white mb-8 tracking-tighter uppercase leading-none">Provisioning</h2>
                   <p className="text-slate-400 text-3xl font-medium">Hardened Cloudflared Installation Script</p>
                </div>
                <div className="glass-card rounded-[5rem] p-16 border border-white/5 shadow-3xl">
                   <p className="text-slate-500 text-xl font-medium mb-10 italic">
                      "Utilize the following hardened script to establish the ZTNA tunnel persistence on your Sovereign Node cluster."
                   </p>
                   <CodeBlock code={SCRIPTS.CLOUDFLARED_INSTALL} />
                </div>
                <div className="flex justify-center">
                   <button onClick={() => setView(AppView.DASHBOARD)} className="px-16 py-7 bg-white text-black rounded-[2.5rem] font-black uppercase tracking-widest text-xs shadow-3xl transition-all">Advance Path</button>
                </div>
              </div>
            )}

          </div>
        </div>
      </main>

      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;900&display=swap');
        .font-inter { font-family: 'Inter', sans-serif; }
        .custom-scrollbar::-webkit-scrollbar { width: 8px; }
        .custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
        .custom-scrollbar::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.03); border-radius: 40px; }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover { background: rgba(59,130,246,0.3); }
        
        .shadow-3xl {
          box-shadow: 0 60px 140px -40px rgba(0,0,0,0.9), 0 0 80px -20px rgba(59,130,246,0.2);
        }

        .animate-spin-fast {
          animation: spin 1.5s linear infinite;
        }

        .animate-spin-slow {
          animation: spin 8s linear infinite;
        }

        @keyframes spin {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
};

export default App;
