"""SynthesisAgent — executive briefing generator using local LLM.

Uses LM Studio (qwen3.5-9b-sushi-coder-rl-mlx) or Ollama fallback to
produce a structured executive briefing from the plan text and extracted
entities. Falls back to a template-based summary when no LLM is available.
"""

from agents.lmstudio import chat_complete
from agents.models import ExtractionResult


_SYSTEM_PROMPT = (
    "You are the Agape Sovereign executive briefing agent. "
    "Your role is to synthesize a sovereign identity workflow plan into a clear, "
    "structured executive briefing. "
    "Focus on: key objectives, critical risks, technical dependencies, "
    "and the security/privacy posture of the system. "
    "Be concise, precise, and use Markdown headers."
)


class SynthesisAgent:
    def run(self, plan_text: str, extraction: ExtractionResult) -> str:
        # Build context summary from regex extraction
        extraction_summary = (
            f"Names: {', '.join(extraction.names) or 'None'}\n"
            f"Dates: {', '.join(extraction.dates) or 'None'}\n"
            f"Financial figures: {', '.join(extraction.financial_figures) or 'None'}\n"
            f"Technical terms: {', '.join(extraction.technical_schematics[:20]) or 'None'}"
        )

        # Truncate plan text for context window safety
        plan_snippet = plan_text[:8000] if len(plan_text) > 8000 else plan_text

        user_prompt = (
            "Produce a concise executive briefing (max 600 words) for the following "
            "sovereign workflow plan.\n\n"
            f"## Extracted entities\n{extraction_summary}\n\n"
            f"## Plan text (truncated)\n{plan_snippet}\n\n"
            "Structure your response with these sections:\n"
            "# Executive Briefing\n"
            "## Overview\n"
            "## Key Objectives\n"
            "## Critical Risks\n"
            "## Technical Dependencies\n"
            "## Security & Privacy Posture\n"
            "## Recommended Next Actions\n"
        )

        briefing, backend = chat_complete(
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            max_tokens=800,
            temperature=0.2,
        )

        if briefing:
            footer = f"\n\n---\n*Generated by {backend}*"
            return briefing + footer

        # Fallback: template-based summary (no LLM available)
        return self._template_briefing(extraction)

    # ------------------------------------------------------------------
    # Template fallback (offline / LLM unavailable)
    # ------------------------------------------------------------------

    def _template_briefing(self, extraction: ExtractionResult) -> str:
        lines = [
            "# Executive Briefing",
            "",
            "## Overview",
            "The workflow orchestrates extraction, synthesis, and audit activities "
            "for the attached sovereign document plan.",
            "",
            "## Key Findings",
            f"- Names identified: {', '.join(extraction.names) if extraction.names else 'None'}",
            f"- Dates identified: {', '.join(extraction.dates) if extraction.dates else 'None'}",
            f"- Financial figures: {', '.join(extraction.financial_figures) if extraction.financial_figures else 'None'}",
            f"- Technical schematics: {', '.join(extraction.technical_schematics) if extraction.technical_schematics else 'None'}",
            "",
            "## Risks, Goals, and Liabilities",
            "- Risk: the plan depends on structured input quality and reliable extraction coverage.",
            "- Goal: produce a complete, auditable workflow report from the source material.",
            "- Liability: missing or ambiguous source content can reduce confidence in downstream outputs.",
            "",
            "---",
            "*Generated by template fallback (no local LLM available)*",
        ]
        return "\n".join(lines)
